version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: circleci/node:15
    environment:
      DATABASE_URI: process.env.MONGODATABASE_URI
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - coveralls/upload
notify:
   webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}